name: Lint App

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Common Deps
        run: npm i --ignore-scripts
      - name: Install App Deps
        run: npm i --ignore-scripts
        working-directory: ./app
      - name: Where Am I
        run: ls
      - name: Lint
        run: npm run lint
        working-directory: ./app
