name: Lint App

on: [pull_request]
defaults:
  run:
    working-directory: ./app

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Deps
        run: npm i --ignore-scripts
      - name: Lint
        run: npm run lint
